### PR TITLE
Enable executing C code

### PR DESCRIPTION
**Pull request by Chris00**

### CODE REVIEW

**Comment by rgrinberg** [comment]
Are there situations where this is necessary? An issue for packages depending on this is that it will break cross compilation. Since it's impossible to run these C programs on the target switch when cross compiling.

cc @dra27

**Comment by Chris00** [comment]
See https://github.com/janestreet/configurator/issues/6

In my case, it is for FFTW3 where I have
```C
enum fftw_r2r_kind_do_not_use_me {
     FFTW_R2HC=0, FFTW_HC2R=1, FFTW_DHT=2,
     FFTW_REDFT00=3, FFTW_REDFT01=4, FFTW_REDFT10=5, FFTW_REDFT11=6,
     FFTW_RODFT00=7, FFTW_RODFT01=8, FFTW_RODFT10=9, FFTW_RODFT11=10
};
```
and I want to perform a test making sure the numerical values have not changed because I convert them to a sum.

**Comment by rgrinberg** [comment]
I see, so would this be a required part of the build? It would be nice if your fftw bindings were possible to cross compile.

**Comment by Chris00** [comment]
It is part of the build to avoid a program to segfault because the underlying library changed and the bindings did not.  It could be made part of tests but this would be less effective in preventing this behavior.

**Comment by Chris00** [comment]
How is cross-compilation achieved when reading C defines or checking that some C code compiles?

**Comment by rgrinberg** [comment]
> How is cross-compilation achieved when reading C defines or checking that some C code compiles?

Well you can compile code for the target, you just can't run it. So checking if things compile is no problem. Reading C defines can be done by only running the preprocessor using the `-E` flag.

**Comment by Chris00** [comment]
> Well you can compile code for the target, you just can't run it.

Right.  I was more thinking about the environment in which programs are compiled since the correct version of the library has to be located.  In my case, knowing the right location of `fftw3.h` would allow me to (minimally) parse it to ensure correctness.

Another possibility would be to have a flag saying that cross-compilation is taking place and avoiding running the program in that case — maybe in configurator itself.

**Comment by rgrinberg** [comment]
> In my case, knowing the right location of fftw3.h would allow me to (minimally) parse it to ensure correctness.

You should be able to locate the correct header if pkg-config is being used. It's fairly easy to control pkg-config to use host vs. target libs appropriately so that shouldn't be a problem.

**Comment by Chris00** [comment]
> You should be able to locate the correct header if pkg-config is being used.

Do you have in mind to use `--cflags-only-I`?  If it is installed at a standard location — does it necessarily mean `/usr/include/`? — nothing is printed.  What is the *robust* way (that is cross-compiling safe) you recommend to get the path to a C header file?

**Comment by Chris00** [comment]
@rgrinberg What about using [gcc](http://www.mingw.org/wiki/includepathhowto), [clang](https://groups.google.com/a/chromium.org/forum/#!topic/clang/z4O8AJ7kT6I) or [msvc](https://docs.microsoft.com/en-us/cpp/build/reference/showincludes-list-include-files) to get the full path to a `.h` file and so be able to open it for parsing?  Since this would use the cross-compiler, that would be portable.

**Comment by rgrinberg** [comment]
Christophe Troestler <notifications@github.com> writes:

> @rgrinberg What about using [gcc](http://www.mingw.org/wiki/includepathhowto), [clang](https://groups.google.com/a/chromium.org/forum/#!topic/clang/z4O8AJ7kT6I) or [msvc](https://docs.microsoft.com/en-us/cpp/build/reference/showincludes-list-include-files) to get the full path to a `.h` file and so be able to open it for parsing?  Since this would use the cross-compiler, that would be portable.

Yes, that seems promising. Running the C file should be a last resort.
Sorry for not replying earlier, I haven't done serious experimentation
on the front of cross compiling C stubs. So I don't really have much to
add here. I'd like to see how ctypes is going to fit in this system as
well, and then I think we'll have all the pieces for X compilation for c
stubs.

**Comment by rgrinberg** [comment]
@Chris00 I think all the issues here have been addressed in the new configurator.

**Comment by Chris00** [comment]
Right.  I'm closing this.

**Pull request closed without merging**
